### ISSUE TITLE
Equivalent to XLabs HybridWebView RegisterCallback()

### ISSUE THREAD

**Issue by acicovic** [SKLn-Rad/Xam.Plugin.Webview#1]
Hi there,

First of all thank you for your work. I think that your Webview will become increasingly popular now that XLabs officially states that their Forms project is no longer maintained. I do not know if you've started working on some documentation, but I think it could really help with adoption, especially for developers who start working on Xamarin.Forms (like me).

The XLabs HybridWebView provides a RegisterCallback() function. When the Native() function is called within Javascript, we use the RegisterCallback function to assign it to a C#/VB function.

Surely there is an equivalent in your Webview?

Thank you for your time!

**Comment by SKLn-Rad** [comment]
Hey man,
Thanks for your feedback, I was aware that XLabs provided this functionality and it is defiantly in the roadmap! The basis of that functionality as I am sure you're aware relies on serialising the data between the JS bridge and then using a name to map that to an action. It was for this reason I choose to avoid it initially as then it adds the complexity of supporting the native webview of each platform and the differences they may have! For example Samsung devices are notorious for this...

I can add this next update, but its probably worth if your application is targeting lots of different webview implementations, to have a fallback using the OnJavascriptResponse event and InjectJavascript method.

Would the end of this week be too late for this feature?
Regards,
Ryan

**Comment by acicovic** [comment]
Hi Ryan,

Thank you so much for your response and your intention to help. I am currently targeting Android and iOS and I will be happy to have that feature whenever you choose to implement it. I think that it's definitely a feature that many current XLabs Forms users will appreciate.

In the meantime, I will see if OnJavascriptResponse and InjectJavascript can work in my scenario. Can you tell me when/how is the OnJavascriptResponse event triggered?

Regards,
Alex

**Comment by SKLn-Rad** [comment]
No problem Alex.
Currently as per the readme, the injected native function is csharp(string).

So in your Javascript, if you call csharp and pass it a single string it will invoke the OnJavascriptResponse event providing you have a registered action 👍 

Hope this helps,
I will keep you updated on the progress of this feature.

**Comment by acicovic** [comment]
Hy Ryan,

Sorry for not spotting this in the readme.

I did some preliminary testing and csharp/OnJavascriptResponse seems to work perfectly for my purposes, along with InjectJavascript() which sends back Javascript to the WebView to launch functions within it.

Thank you for your all the feedback so far.

**Comment by SKLn-Rad** [comment]
Hey man, I got some time this evening so I put in a version of what you're after.
It will require the Newtonsoft JSON dependency though which should automatically be installed when you update.

Can you let me know if this works for you? I havent had time to test on iOS yet :)
https://www.nuget.org/packages/Xam.Plugin.WebView/1.2.0

**Comment by acicovic** [comment]
Hi,

I will see if I can test this today and let you know.

Thank you for your work!

**Comment by acicovic** [comment]
Hi Ryan,

Before integrating your WebView into my main project, I've created a sort of test project here:
https://github.com/acicovic/FormsWebViewTests

I've only tested it on Android so far and things seem good. The only thing that I've noticed is that the first time it is called, the RegisterCallback method is significantly slower (maybe 2 - 4 times) than the OnJavascriptResponse event. I've not investigated but this might be normal if you're interacting with Newtonsoft JSON.

**Comment by SKLn-Rad** [comment]
Yeah I expect its to do with that... XLabs requires you to attach an IJsonSerializer which basically does the same thing. It could also be down to the bridge adapting itself as when you register a new interface, it will append the method to the DOM itself.

I will have more of a look into it tomorrow, but I don't think its something which can be worked around without manually adding your own JSON serializer with an interface to handle the interaction between the JSBridge.

For the time being though, I will close this as the feature itself appears to work from initial testing and will potentially open an enhancement tomorrow if I can identify a better approach to this problem.

**Comment by acicovic** [comment]
Works in iOS 10.2 (VS 2015 iPhone 6 Simulator, I have no physical device).
