### ISSUE TITLE
File picker support

### ISSUE THREAD

**Issue by azeemchaudhrry** [SKLn-Rad/Xam.Plugin.Webview#105]
Is this plugin support file picker in Android?
because nothing happens if 'choose file' button tapped inside webview.

**Comment by Kauppi** [comment]
In the current version the file picker is not working in Android but I have solved it. It only needs to be merged to the main code. See pull request in this thread https://github.com/SKLn-Rad/Xam.Plugin.Webview/pull/101

**Comment by azeemchaudhrry** [comment]
@Kauppi Thanks!
