### ISSUE TITLE
WebView fails on UWP when in Release Configuration

### ISSUE THREAD

**Issue by ahmedkhan25** [SKLn-Rad/Xam.Plugin.Webview#106]
Currently the Webview control fails to load (blank screen) on UWP when the build config is set to RELEASE 
(Debug works correctly)

Note this might be related to this known issue: https://blog.mjjames.co.uk/2018/05/uwp-webview-intermittently-fails-to.html

Steps to Reproduce: Build and Launch Sample app in X64 RELEASE Config - we see the following:
![uwpbugblankscreen](https://user-images.githubusercontent.com/1980889/44221830-59234100-a148-11e8-86e0-db3ec132420e.PNG)

**Comment by FoggyFinder** [comment]
@ahmedkhan25 

add the next line 

```csharp
[assembly: Xamarin.Forms.Platform.UWP.ExportRenderer(typeof(Xam.Plugin.WebView.Abstractions.FormsWebView), typeof(Xam.Plugin.WebView.UWP.FormsWebViewRenderer))]
```

before

```csharp
namespace SampleApp.UWP
```

in App.xaml.cs

**Comment by ahmedkhan25** [comment]
Thanks! that worked
