### ISSUE TITLE
Problem with site

### ISSUE THREAD

**Issue by beckerpablo** [SKLn-Rad/Xam.Plugin.Webview#11]
Hi,
I´m having a problem showing the url https://t-e-express-dev.onelogin.com/login, I can see just half of the page. How can I solve it?

Thanks in advance.
Pablo

**Comment by SKLn-Rad** [comment]
Hey Pablo,
Its hard to debug problems like this without pictures or any context around what you're getting!

If you need to play about with any native settings, for example trying software rendering on Android, then you can use the OnControlChanging event in the Renderer to modify these properties.

If you could get more for me about your environment then I would be able to help you more!

**Comment by beckerpablo** [comment]
Hi Ryan,

Thank you very much for your fast answer.
I´m going to send you a screen shot, but if you just set the source of that
url you will see half of the page, if you don't, I have the problem. Let me
know if you see half or not.

Thank you,
Pablo

**Comment by SKLn-Rad** [comment]
https://i.snag.gy/xNwLDF.jpg

I tried it using the SampleApp on UWP and it appears to work find using FillAndExpand on both horizontal and vertical options.

What platform are you having this issue on as I will need to run out and grab a device from work?

**Comment by beckerpablo** [comment]
I'm testing with an Android phone, Samsung Galaxy s7.
My xaml code is <formsWebView:FormsWebView Source="https://t-e-express-dev.onelogin.com/login" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" />
What I see is
![screenshot_20170308-125236](https://cloud.githubusercontent.com/assets/26279944/23711451/b5e844b4-03fe-11e7-95d9-20067e558a54.png)

**Comment by SKLn-Rad** [comment]
Thanks for this, I have heard weird things about that particular phone but I won't be able to test myself on an Android device for another 2 hours or so.

In the meantime, can you try adding this before your Forms.Init() in Android.MainActivity?

FormsWebViewRenderer.OnControlChanging += (sender, element, control) =>
            {
                var webView = control as Android.Webkit.WebView;
                webView.SetLayerType(LayerType.Software, null);
                webView.Settings.LoadWithOverviewMode = true;
                webView.Settings.UseWideViewPort = true;
            };

**Comment by beckerpablo** [comment]
Thank you very much.

I tryed the code but nothing changed.

Pablo

**Comment by TobiasKullblikk** [comment]
Did you find a solution to this? I'm having the exact same issue with another login page.

**Comment by SKLn-Rad** [comment]
Hey guys, I can't say off the top of my head that I know whats going on here, but I suspect its to do with the native webview underlying those devices.

Would one of you be able to get me a simple sample app with one of those login pages so I can have a look myself?

Thanks!

**Comment by beckerpablo** [comment]
I send a simple xaml test. The solution is more than 60mb and I cant upload. tha page doesnt work in Android but work in iOS.

Thanks.

[MainPage.zip](https://github.com/SKLn-Rad/Xam.Plugin.Webview/files/1180980/MainPage.zip)

**Comment by SKLn-Rad** [comment]
FOUND IT! Due to Xamarin abstraction, the parent layout never had parameters to set its width/height. And instead of calculating this if its null, Android will only submit this information to the website if it is set. So the Website had a calculated CSS height of 0px.

I have forced the webview to always match parent in 1.6.1 and managed to get it working on my phone. Do let me know if you get the same so I can close this bug. :)

**Comment by beckerpablo** [comment]
hey you are the best!!!! You deserve some beer this week! Send me a paypal
link! Thank you very much!!!




*Pablo Becker*
*3Pi Factory - Business Solutions*
Av. Pueyrredon 538 Cuerpo 2 PB 2 - C1032ABS - Buenos Aires - Argentina
t. +54 11 5917.5858 Ex.102
c. +54 9 11 5842.7777
*www.3pifactory.com*
<https://mailtrack.io/trace/link/f5f2a65cd7d5ee765e0636c7399cc81ac09b7f09?url=http%3A%2F%2Fwww.3pifactory.com%2F&userId=853685&signature=d03714e2407333da>

**Comment by SKLn-Rad** [comment]
If you must haha, its on the readme (you dont have to though) :)
@TobiasKullblikk  can you attempt this build to see if it also is fixed for you? If not I will close this ticket.
