### ISSUE TITLE
PopToRootAsync cause app to crash

### ISSUE THREAD

**Issue by IeuanWalker** [SKLn-Rad/Xam.Plugin.Webview#112]
Calling PopToRootAsync causes the iOS app to crash.
I have tried putting a try/ catch around it but the app just get terminated.

**Comment by manuchevreux** [comment]
Try to use this :

>  public Task BeginInvokeOnMainThreadAsync(Action action)
>         {
>             TaskCompletionSource<object> tcs = new TaskCompletionSource<object>();
>             Device.BeginInvokeOnMainThread(() => {
>                 try
>                 {
>                     action(); tcs.SetResult(null);
>                 }
>                 catch (Exception ex)
>                 {
>                     tcs.SetException(ex);
>                 }
>             });
>             return tcs.Task;
>         }
> 
>            BeginInvokeOnMainThreadAsync(() =>
>                 {
>                     //PopToRootAsync 
>                 });

**Comment by IeuanWalker** [comment]
@manuchevreux also it seem to only an issue on iOS 12

**Comment by IeuanWalker** [comment]
@manuchevreux also it seem to only an issue on iOS 12

**Comment by IeuanWalker** [comment]
Issue fixed.

Seems to be an issue with the default Xamarin webview.
Here is more about it + the fix = https://github.com/xamarin/xamarin-macios/issues/4130

It is a problem with how they release/ remove the webview that causes a random crash.

At the moment the fix isnt released but is expected to be some time this fall.
To fix this issue now though, download and run the following file on you mac (the build machine) - [xamarin.ios-12.0.0.16](https://bosstoragemirror.blob.core.windows.net/wrench/jenkins/PR-4867/a687249101f68689c1715732194dac7798b26a78/2/package/xamarin.ios-12.0.0.16.pkg)
The above file is the latest Xamarin.ios 12.0 and the fix.
