### ISSUE TITLE
Page load failed event

### ISSUE THREAD

**Issue by ameli72** [SKLn-Rad/Xam.Plugin.Webview#12]
Hi, Is there a way to detect if the url you are attempting to load fails?
Thanks

**Comment by SKLn-Rad** [comment]
Hey,
At the moment I have no added any unified error handling, however it is defiantly in my TODO list! I just have not planned how the API's are going to work yet to expose the error to the user. If you have any ideas I would love to hear them.

For the time being, I exposed all of the controls so you can add your own logic to the native controls.
If you add an event for OnControlChanging in the startup before the init call, then you can use the control parameter and cast it to the WebView of the platform you are targeting.

WKWebView for iOS
WebKit.WebView for Android
UI.Controls.WebView for Windows

If you don't want to do that, then I can probably aim to get a "temporary" implementation done by the end of this week, given that you're aware that it may change.

Regards,
Ryan

**Comment by ameli72** [comment]
Thanks for your reply! I will try and make those changes later this week and will keep you posted on how it went. Cheers again

**Comment by SKLn-Rad** [comment]
Closing as haven't heard anything in 5 days! Please feel free to contact me if you have any more issues!
