### ISSUE TITLE
Qussion About RegisterCallback respone parameter

### ISSUE THREAD

**Issue by Doughouzlight** [SKLn-Rad/Xam.Plugin.Webview#13]
Hi 

Thank you for this nice plugin 

my problem is i want to pass some parameter via javascript function 
Here is my code for RegisterCallback 

` PostWebLoader.RegisterCallback("test", (str) =>
 {
     Parmeter = str;
     Debug.WriteLine(str);`
});`

and in my website i am using the function as like this >>
csharp(test,somthing)

So How i can pass the **somthing** to my respond and fire it on OnJavascriptResponse

Regards

**Comment by SKLn-Rad** [comment]
Hey man,
When you register a callback using RegisterCallback(string, action<string>) it will automatically inject a new function into each page as you navigate throughout your website.

If you just call test(something) from your Javascript then it should be fine. If what you're returning is not a string then you can serialise it and send it over as JSON as an example.
Complete code would look like this for example =>

C#:
WebView.RegisterCallback("submitDocumentTitle", (str) => Debug.WriteLine(str));

Javascript:
$( document ).ready(function() { submitDocumentTitle(document.title); });

Let me know how you get on so I can close the issue if this sorts it!

Regards,
Ryan

**Comment by Doughouzlight** [comment]
Hi Ryan

My point is i have a click event on javascript on my website **onclick="Clickme()"**
i want when i press on the post to let it pass to me some parameters like POSTID or USERID from the post 

Then i want to display it as **DisplayAlert()** in my android platform with the values

should i add the **csharp('test','valuePassed')** or as your java script code ? 


my code on website looks like this **csharp('test','valuePassed')** inside the **Clickme()** function
i have tested your code , but the **OnJavascriptResponse** functions don't fires 


I am working on it or more then 7 hours on your plugin 

i think you can just help me for it 

Regards 

Allen

**Comment by SKLn-Rad** [comment]
Hey Allen, sorry about the slow response.

csharp(string) only takes the one parameter so you cannot overload it with multiple strings. You will have to send it up formatted in some way. For example csharp('{"test" : "valuePassed"').
If you still cannot get a javascript response back, then make sure you have the correct privileges in the app packages for your platforms.

If it is easier, I did hook in the native alert controls so you should be able to simply call alert from javascript if thats all you're trying to do.

Let me know how you get on, sorry for not understanding the first time!

~ Ryan

**Comment by SKLn-Rad** [comment]
Closing as haven't heard anything in 3 days! Please feel free to contact me if you have any more issues!

**Comment by Doughouzlight** [comment]
Hi Reyan

Sorry for late answer , i am passing the agrument as you told by this code >> 

`csharp('{"test" : "valuePassed"').`

It works fine , but inside the browser i have a java script button when a user press on this button he gets new posts , but the new post are not RegisteredCallback it dont works if i click on them 

Any idea how to should i do it ? 

Regards 

Allen
