### ISSUE TITLE
Handling Back Button

### ISSUE THREAD

**Issue by atkinsonline** [SKLn-Rad/Xam.Plugin.Webview#16]
Hi Ryan,
Firstly, thank you for making this available and providing support. Mine is more of a question than an issue.  Is there a better place to ask questions? I'm a mobile developer but do not have much experience of either Xamarin or webviews so my problem could be a simple one but I'm struggling to figure this out. I suspect my question is not really an issue with your webview. 

I need to handle the back button with some kind of intelligence.  Currently, if I press the hardware back button in Android I'm taken back to the android home screen. For Android, I think I need to do something like this in the android project
```
public override void OnBackPressed()
        {
            var webView1 = FindViewById<Android.Webkit.WebView>(Resource.Id.webView);
            if (webView1.CanGoBack())
                webView1.GoBack();
            else
            {
                base.OnBackPressed();
            }
        }
```
The above could be completely wrong in the context of your webview. My test program is basically your sample where the webview is created in the portable app.cs and I can't figure out how to reference the WebView in Android's MainActivity.cs.  
Thanks

**Comment by SKLn-Rad** [comment]
Hey man, there is two ways you can go about this. The application doesn't automatically pass a hardware back button press to the WebView. Instead in Xamarin this is a method in the Page object which you can override.

public class ContentPage {
    public override bool OnBackButtonPressed() {}
}

If I recall, you return true if you want the application to ignore the back button press and false if you want to pass it back (go back in a navigation page or go back to the home screen)

In terms of obtaining the WebView in the Android project you can get it using the ControlChanged event.

Add the following to your MainActivity:

FormsWebViewRenderer.OnControlChanged += (renderer, element, control) => {
var webView = (WebView) control;
}
This will cast the control as a WebView in order for you to obtain later :)

Another option would be to use Javascript callbacks:
FormsWebView.InjectJavascript("window.location.back();"); or something like that...

I presume this is being used in a Forms project or am I wrong?

**Comment by atkinsonline** [comment]
Thank you for the very quick response and for answering a question which is more related to Xamarin than your plugin.  I have a lot to learn :-)
Yes, this is a Forms project.  It's basically your sample code that I've built upon to test the scenario I need to handle.  I need to invoke the camera and access photos from a webview.  Your plugin has provided me with much of what I need. 
I had to cast as an explicit Android.Webkit.WebView or it got confused
```
 thisWebView = (Android.Webkit.WebView)control;
```
I couldn't get the override of `OnBackButtonPressed` to work but I found I was able to use the following in MainActivity and it seems to work.
```
        public override void OnBackPressed()
        {
            if (thisWebView.CanGoBack())
                thisWebView.GoBack();
            else
            {
                base.OnBackPressed();
            }
        }
```
Thank you for your help.

**Comment by SKLn-Rad** [comment]
Absolutely no problem and thanks for the support. If at all i can add any features or provide any more sample code then of course let me know.

- Ryan
