### ISSUE TITLE
Android EventObj.uri gives whole WebView Source

### ISSUE THREAD

**Issue by mwpb** [SKLn-Rad/Xam.Plugin.Webview#18]
Hi and thanks for your work on this webview! We are trying to use add_OnNavigationStarted to communicate from javascript to fsharp. (In passing if the register callback method is to be prefered please let me know!) Our method starts by calling some javascript to navigate the page:

```
<script>
    function getHeight() {
        var main = $('#mainUniqueName');
        var h = main.height();
        window.location = 'http://comm/?HWVHeight=' + h.toString();
    }
</script>
```

then we catch this and decode the uri string:

```
t.add_OnNavigationStarted
        (
            fun e ->
                let s = e.Uri
                Debug.WriteLine("Navigating to: "+e.Uri+" . ")
                if s.StartsWith("http://comm/?") then
                    e.Cancel <- true
                    let instr = "http://comm/?"+name+"="
                    let n = instr.Length
                    if s.StartsWith(instr) then
                        let decoded = s.[n..s.Length-1] |> System.Uri.UnescapeDataString
                        decoded |> f
                e
                )
```

On UWP this works exactly as expected and the Debug.WriteLine above gives:

```
Navigating to: http://comm/?HWVHeight=602 . 
```

However on Android the whole source of the WebView is appearing:

```
Navigating to: 
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="utf-8"/>
    <script src="file:///android_asset/miniMathJax/MathJax.js?config=TeX-AMS_SVG"></script>
    <script>MathJax.Hub.Config({tex2jax: {inlineMath: [['$','$']]},imageFont: null, messageStyle:"none"});</script>
    <script type="text/javascript" src="file:///android_asset/jsxgraphcore.js"></script>
    <script src="file:///android_asset/jquery.js"></script>
    <style>
        * {
            font-size: 18pt;
        }
        </style>
  </head>
  <body>
        <div id='mainUniqueName'> 
            ... some long html string here... </div>
        <script>
            function getHeight() {
                var main = $('#mainUniqueName');
                var h = main.height();
                window.location = 'http://comm/?HWVHeight=' + h.toString();
            }
        </script>
    </body>
</html>
 . 
```

(Please note the trailing full stop - this isn't some other debug output.) Is this expected behaviour, or I have made some kind of mistake? I can provide more details if required.

**Comment by mwpb** [comment]
Please find a mve:

https://github.com/mwpb/NavigationStartedEventUri

Also we are probably going to go with the RegisterCallback approach for our actual project but I'm still curious about this approach also.

**Comment by SKLn-Rad** [comment]
Hey man,
Nice find! It was due to the NavigationStarted event being fired too early (before the WebView got a valid URI) which was due to a result of the hack I added for pre Android M http error handling.

I have updated the code to reflect this and have removed the hack (pushing minimum Android version support to 5.0 unfortunately :( ), but at least it should be working for your use case now!

Might take 5 minutes to index, letme know how you get on so I can close this 👍 

~Ry

**Comment by mwpb** [comment]
Hi! Can confirm that the fix works for the mwe. Our codebase is now using the register callbacks so I cannot check it further there. So I guess that means this should be closed!

**Comment by SKLn-Rad** [comment]
Great news! feel free to pm me if you need anything else.

**Comment by mwpb** [comment]
Hi, just double checked and it works on the other project too. Thanks for your quick response!
