### ISSUE TITLE
NuGet Package Manager - Error

### ISSUE THREAD

**Issue by acicovic** [SKLn-Rad/Xam.Plugin.Webview#2]
Hello there,

When I open the NuGet package manager and go to the "Installed" tab, it displays an "Error occurred" notice. In the output I get errors like: 

Item has already been added. Key in dictionary: 'lib/win81/WebView.Plugin.Abstractions.dll'  Key being added: 'lib/win81/WebView.Plugin.Abstractions.dll'
Item has already been added. Key in dictionary: 'lib/win81/WebView.Plugin.Abstractions.dll'  Key being added: 'lib/win81/WebView.Plugin.Abstractions.dll'
Item has already been added. Key in dictionary: 'lib/win81/WebView.Plugin.Abstractions.dll'  Key being added: 'lib/win81/WebView.Plugin.Abstractions.dll'
Item has already been added. Key in dictionary: 'lib/win81/WebView.Plugin.Abstractions.dll'  Key being added: 'lib/win81/WebView.Plugin.Abstractions.dll'

I was getting this on a project and thought that I had messed something up, but my test project (https://github.com/acicovic/FormsWebViewTests) has the same issue so I think it might have to do with the plugin?

Thank you for your work!

**Comment by SKLn-Rad** [comment]
Thanks for the bug finding Alex.

I think I found the bug which causes this error, but it doesnt seem to occur when you're using newer versions of the NuGet package manager. Would you be able to try 1.2.1 and see if that fixes it :)

Thanks,
Ryan

**Comment by acicovic** [comment]
Hey Ryan,

Great job, this fixes it for me. I am using NuGet Package Manager 3.4.4.
