### ISSUE TITLE
FormsWebView has transparent background somehow. e 

### ISSUE THREAD

**Issue by gogobebe2** [SKLn-Rad/Xam.Plugin.Webview#20]
Is this normal? It looks cool though. The background is the default background I use in the MainPageTemplate ControlTemplate. I'm not complaining because I'm planning on making a background webview task that is invisible. But I thought I'd bring this up.

![image](https://cloud.githubusercontent.com/assets/6384447/25608058/86310662-2f6d-11e7-9b18-5e54258e9ec6.png)

```
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="TheDayAhead.TimetablePage"
             ControlTemplate="{StaticResource MainPageTemplate}"
             xmlns:local="clr-namespace:TheDayAhead;assembly=TheDayAhead"
             xmlns:controls="clr-namespace:Xam.Plugin.Abstractions;assembly=WebView.Plugin.Abstractions"
             NavigationPage.HasNavigationBar="false">

    <StackLayout x:Name="sl">
        <controls:FormsWebView x:Name="FormsWebView_Main"
                      HorizontalOptions="FillAndExpand"
                      VerticalOptions="FillAndExpand"
                      Source="http://www.google.com"/>
    </StackLayout>
</ContentPage>
```

**Comment by SKLn-Rad** [comment]
Yes this is normal! Unless the website specially declares a background colour in its CSS or a background colour is set on the FormsWebView object itself, it will resolve as transparent 👍

**Comment by gogobebe2** [comment]
That's actually awesome.
