### ISSUE TITLE
Calling a JavaScript function from CSharp

### ISSUE THREAD

**Issue by atkinsonline** [SKLn-Rad/Xam.Plugin.Webview#22]
Hi, I've been using your plugin very successfully to inject javascript and call C# from the injected javascript.  I also have the need to call one of the injected javascript functions from C# and just wanted to make sure I've not missed some functionality provided by the plugin.  I have managed to call a JavaScript function myself from C# but it is quite complex especially if you need to asynchronously wait for a response.
My questions are, is this already provided and if not do you have any plans to add this functionality?
Thank you, John.

**Comment by SKLn-Rad** [comment]
Hey John,
At the moment there is only functionality to run this functions
asynchronously as no platform has a "recommended" way to achieve it
synchronously.

Of course there is the option of spawning another thread as a listener, but
I have no plans to implement this at the moment as it would most definitely
be a hack.
However if it is something which would help you significantly then I don't
mind adding a wrapper into the next release to provide functionality like
this.

If you have any suggestions on how such an API would be implemented then
please let me know :)

- Ryan

**Comment by atkinsonline** [comment]
Hi Ryan,
Thank you for the very quick answer.  I mainly wanted to make sure I hadn't missed anything in the existing functionality.  So far what I've done is working but it has had little testing yet. All I did was prove that it could be done.
I'll get back to you if I have any suggestions for how the plugin could be improved.  I suppose it also depends on whether other people would find it useful.  Not worth it for a one-off!  Feel free to close this.
Regards, John.

**Comment by SKLn-Rad** [comment]
No problems, yeah looking into it it would 100% involve injecting my own javascript to monitor when functions complete and then returning based on a time threshold. I will keep an eye out as I have some other things in the pipeline first which are probably more useful!

Thanks again,
Ryan

**Comment by atkinsonline** [comment]
Thank you.  I look forward to any new features.
