### ISSUE TITLE
Catching NSErrorException

### ISSUE THREAD

**Issue by madcreep** [SKLn-Rad/Xam.Plugin.Webview#24]
Hi there.

Is it possible to add try/catch block into InjectJS method so that NSErrorException could be caught and some event with info which particular script led to the exception raised?

**Comment by SKLn-Rad** [comment]
I could definitely throw the exception up for you, however any problems you get _should_ be in the Javascript and ideally should be handled there anyway!

The code is pretty simple ->

```c#
internal void InjectJS(string js)
{
    if (Control != null)
        InvokeOnMainThread(async () => await Control.EvaluateJavaScriptAsync(new NSString(js)));
}
```

**Comment by madcreep** [comment]
The thing is, when something's wrong with the Javascript, an exception on the main thread is being raised and the whole application is being crashed.

**Comment by SKLn-Rad** [comment]
Sure, I will have to look into how I would go about this more as other platforms "Windows", will always crash if the Javascript is bad and there is no way around this. So having an error catching mechanism could be confusing if it is only supported by two platforms.

When I get some time later I will start to have a look at this.

**Comment by madcreep** [comment]
Thanks!

**Comment by SKLn-Rad** [comment]
Closing as platform limitation in UWP. The app will always crash if a JS exception is thrown.
Ideally the best solution would be to try catch along the bridge and globally handle JS exceptions.

Will reopen if a solution comes out with the new UWP variant but until then alas :(
