### ISSUE TITLE
NuGet Import Error

### ISSUE THREAD

**Issue by rikkuporta** [SKLn-Rad/Xam.Plugin.Webview#27]
Hi!
Upon building of the sample project I get this error:
/Users/matthias/Desktop/Xam.Plugin.Webview-master/WebViewPlugin/WebView.Plugin.Abstractions/WebView.Plugin.Abstractions.csproj(5,5): Error: This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ../../../../vistair-xamarin/vistair-docunet/trunk/packages/Xamarin.Forms.2.3.4.247/build/portable-win+net45+wp80+win81+wpa81+MonoAndroid10+Xamarin.iOS10+xamarinmac20/Xamarin.Forms.targets. (WebView.Plugin.Abstractions)

**Comment by SKLn-Rad** [comment]
Sorry for the massively delayed response! Thats my fault for using absolute paths in my csproj. I will fix that up and get a package up asap. For the meantime you can just update the references to the Webview project in your IDE 👍

**Comment by SKLn-Rad** [comment]
I updated the sample app and it should be fixed. If this is not the case, then remove the references to Xam.Plugin on the PCL and the Platform you wish to execute and readd them manually! :)
