### ISSUE TITLE
Request for adding MIT license

### ISSUE THREAD

**Issue by Karthikeyan-tv** [SKLn-Rad/Xam.Plugin.Webview#28]
Hi,

I'm developing the mobile application using Xamarin.Forms and i need to use you WebView plugin and it perfectly suits to my requirements. But i can't use it since there is no MIT license provided explicitly.

So, Can you add MIT license for this plugin?

Thanks,
Karthik

**Comment by SKLn-Rad** [comment]
Done! :)
