### ISSUE TITLE
Navigation stack

### ISSUE THREAD

**Issue by SirLanceLang** [SKLn-Rad/Xam.Plugin.Webview#29]
Is there anyway I can have control or access the navigation stack? (.CanGoBack, GoBack(), etc)
I can see that the hybridview derives from View and not from Webview.

**Comment by SKLn-Rad** [comment]
I can't believe I missed this!
They have been added in 1.6.0 :)

Let me know if they work as you expect so I can close this ticket!

**Comment by SirLanceLang** [comment]
Hi Ryan, I ended up going another way, and found another solution to the problem I had. I dont use your webview for now. If I get back to it, I will be happy to test it, if no one else has. Thank you anyway for your quick response.
