### ISSUE TITLE
iOS: WebView does not show alert()

### ISSUE THREAD

**Issue by acicovic** [SKLn-Rad/Xam.Plugin.Webview#3]
Hi,

I am testing on iOS 10.2 in Visual Studio 2015 iPhone 6 Simulator. I've noticed it's not possible to launch Javascript alerts within the WebView. This might be of interest to you:

http://stackoverflow.com/questions/26898941/ios-wkwebview-not-showing-javascript-alert-dialog

Do you plan to implement this in your WebView, or should it be up to the developer to do it?

Thanks!

**Comment by SKLn-Rad** [comment]
Hey man, sorry if I don't reply as fast as I have just woken up!
Generally rule of thumb is that if its something which can be easily handled across all platforms then yeah I can implement it easily.

If you need the functionality quickly then by all means feel free to add it using the OnControlChanged event, but it is defiantly something I will be adding in the near future. Most likely after I finish an app release so tomorrow?

**Comment by acicovic** [comment]
Hi Ryan,

Tomorrow's perfect.

Thank you for your work.

**Comment by SKLn-Rad** [comment]
Once again, sorry for the delay.
I added the missing methods in the iOS WKWebView UIDelegate to cause the alerts, confirmations and simple text entries to appear.

Once again, would you be able to test this in 1.2.1? It may still not work on UWP yet but I will create another enhancement story for that as I think it may be trickier.
Thanks a lot!

**Comment by acicovic** [comment]
Hi Ryan,

I've tested alerts and they work but with the flaw that program execution continues without waiting for the user's confirmation (pressing OK button). Android behaves correctly (waiting user to press OK to continue execution).

I'm unsure you might be able to do something about it since it might be internal to the WKWebView. For me this issue doesn't cause any trouble at the moment, but if the WebView's userbase grows it's something that'll come up sooner or later.

Thank you for your responsiveness all the work you've been putting into this.

**Comment by SKLn-Rad** [comment]
Yeah I think that may be a limitation of WKWebView as you cannot even hook into window.alert without it throwing an error. Ideally you would handle all of this with events inside of your JS anyway so for now I will probably ignore it unless its required by anyone else... I expect people would be using a more custom version of alert anyway such a jquery sweetalert or equiv.

Closing for now :)
