### ISSUE TITLE
Late callbacks

### ISSUE THREAD

**Issue by jimmyvanhest** [SKLn-Rad/Xam.Plugin.Webview#34]
I have an issue with the RegisterGlobalCallback function.

When I load my webpage in it tries to find some functions I have registered in the DOMContentLoaded event but fails to find it at that moment. When the page is finished loading I execute the JS in the console to check why the functions are not found but this time it finds them.

The weird thing about this is that i call RegisterGlobalCallback  before i set the site source.

Do I need an even later event to check whether the js functions are available?

**Comment by SKLn-Rad** [comment]
This sounds very platform specific. I know Windows had some bugs which sounded exactly like this.
Would you be able to do me a favour and let me know how you're able to reproduce this?

i.e: Platform, Version, and maybe some code?

Thanks in advance,
Ryan

**Comment by SKLn-Rad** [comment]
Closing as no response
