### ISSUE TITLE
Setting request headers

### ISSUE THREAD

**Issue by FlammableFork** [SKLn-Rad/Xam.Plugin.Webview#36]
I really enjoy having this plugin available, however, is it possible to set a header value for a given request, perhaps in an OnNavigationStarted event handler?  Or is there any other current or potential way to handle this?

**Comment by SKLn-Rad** [comment]
Honestly I knew this would be asked sooner or later, but there was never any need for me to have it personally! Its an easy thing to add though so I don't mind taking it on.
Would end of this week be too late for you as I am rather busy at the moment?

**Comment by FlammableFork** [comment]
Thank you for being willing to jump on this so quickly.  End of week would be perfect.

**Comment by SKLn-Rad** [comment]
There is a preview in 1.7.0-rc1, you will have to enable pre-releases. Once I do a tad more testing I will make it an actual release, but until then it should be fine! let me know how it goes :)

**Comment by FlammableFork** [comment]
You were a lot faster getting this out than I expected.  Thank you.  I have request headers working now in my app.  There are a couple of items that are either not working properly, or my expectation about how they work is flawed.

Anytime I try to add request headers in my OnNavigationStarted event handler, they don't appear to arrive at the destination (I'm adding them to eventObj.Sender.RequestHeaders).  This forces me to add the request headers just after registering my callback(s).  This works great for the first request, however subsequent requests do not have the headers.

This last item isn't directly related to the request headers, but it affects setting them.  The website that I am navigating to initially goes through a couple 302 redirects (all on the same server) before I arrive at my final destination.  When trying to get request headers working in my OnNavigationStarted event handler, I noticed that each redirect triggered the event.  Each time this event fired, I received either the same NavigationRequestedDelegate or at least the same eventObj.Sender as a part of the delegate.  This caused an exception because the same request headers were being set each time the event fired (and the headers were already set).  I got around the exception by removing the headers and then immediately re-adding them (less than ideal).

So far, I have done all of my testing using my UWP app, but I would be happy to test further and/or provide any additional details as needed.

**Comment by SKLn-Rad** [comment]
Hey man,
The reason why you cannot set them on navigation started is solely down to an iOS limitation! You literally need to set them before you even construct the request in WKWebView else they won't ever show up :(

The redirect is probably very much the same, I;m hooking into the native bindings for navigationstarted and completed. So the behaviour you're seeing is probably default to UWP. You should be able to do two way binding to the dictionary if you want to handle it yourself to avoid the duplicate entries however.

I will have a look to see if I can get around that WKWebView issue tomorrow, I don't have a Mac at home so I am having to do all of my iOS testing from work unfortunately!

**Comment by SKLn-Rad** [comment]
Hey man, OnNavigationStarted is called after the request has been constructed so there is nothing I can do about this.
Sorry about this, closing as a platform limitation.
