### ISSUE TITLE
osx 

### ISSUE THREAD

**Issue by joeblew99** [SKLn-Rad/Xam.Plugin.Webview#38]
Is is possible to make a webview that works on mac also ?

**Comment by SKLn-Rad** [comment]
Already answered this in another ticket!
I am currently in the process of testing a 2.0 version to come out in line with Xamarins next stable release. That way I can remove support for WinRT, merge to netstandard, and provide support for MacOS all in one release.

I can merge one of my branches back to origin (here) so you can use it if you want, but I won't be able to do that until later this week as I don't have a Mac at home to test on :(

Let me know your thoughts
Ryan

**Comment by joeblew99** [comment]
sorry about that. did not see the other issue.
but thanks for super quick reply...

i am using the Vs for mac (preview) on the alpha channel so am on .net Standard 2.0 as they call it.
If that what you mean about 2.0 ?

**Comment by SKLn-Rad** [comment]
Thats cool man, I'm not too sure what the defaults are for VS for Mac, but it depends on your csproj file.
It will contain <Project Sdk="Microsoft.NET.Sdk"> as the first line if it is using netstandard.

You don't have to worry about it too much, its mainly just to make my life easier as a library developer as I don't then have to target a load of PCL targets. It should be as easy as just installing for you when I make my plugin compatible.

If I get some time tomorrow, I will merge it back into github and let you know. I need to do a 1.7.0 stable release first. But I expect I should be able to get MacOS fully supported within the month depending on Xamarin's roadmap. Did you need this feature sooner?

**Comment by joeblew99** [comment]
I closed the other issue. Again opps a daisy...

No super duper rush. When you think you will get there let me knwo and i will test.

On a side note, I did c# for 10 years but left it to do golang for the last 3 years. But i am stil getting up to speed on .NET on on windows.. There are so many terms now.. PCL, .NET Standard, Core, FX blah blah. So will yu move to .NET Standard 2.0. As far as i can understand this means that PCL is redundant than and it will be easier base.

**Comment by SKLn-Rad** [comment]
That's exactly why. Since you left everything's fine haywire, so netstardard is their way to merging it all back. Doesn't mean PCL is redundant, but it means you will be able to consume a lot more libraries without them needing to explicitly target PCL111 and 257 for Xamarin :)

**Comment by joeblew99** [comment]
thanks for the clarification....

Hit me up when your ready for someone to test it using Xamarin.mac.

I only new 2 things btw:
1. Load a web Views (its a SPA - Single page app) built with Polymer.
2. Have some basic Interop from inside the web view to call c# and visa versa. Also know as a JS bridge.  

The Architecture, which you might be curious about:
1. I run a Service on the device that is written in golang that exposes a http & websocket port and has the DB. Very easy with golang.
2. The GUI app is built with Xamarin and it calls into the Service for the html to load the initial SPA, and then gets and sets data to the Service.

SO i really just use the c# / Xam stuff for running a GUI webview and also doing deeplinking, Notifications and that sot of stuff that webview suck at.

**Comment by SKLn-Rad** [comment]
Done. Make sure to read the migration guide as 2.0.0 is a lot different than 1.*. 👍 

Do let me know if you have some issues. Testing would be appreciated :)
