### ISSUE TITLE
Feature Request: LoadContent function

### ISSUE THREAD

**Issue by acicovic** [SKLn-Rad/Xam.Plugin.Webview#4]
Hi Ryan,

Today I was experimenting with loading a local image into the WebView by calling it in HTML code. As it currently stands (if I'm not mistaken), in order to load local content we must Use the approach described [here](https://developer.xamarin.com/guides/xamarin-forms/user-interface/webview/#Local_HTML_Content) and then set the WebView's BasePath property.

This works but it takes some steps to write code within platform-specific projects so it would be nice to have something like a LoadContent(string content, string baseUri) function which would get the platform's basepath for us, append to it the BaseUri specified in the arguments and then push the string content into the WebView.

Besides making things a bit easier, I think that it is also semantically better as WebView.Uri is not that semantic when we want to load HTML.

XLabs HybridWebView provides a LoadContent method if you want to take a peek at it, although If I recall correctly it still needed special handling for iOS (which again complicates things a bit and would be best avoided if possible). I think that a lot of people coming from XLabs HybridWebView will find it a lot easier if you provide an equivalent function.

Well, thank you for all your work!

**Comment by acicovic** [comment]
Just FYI, I tried to implement the solution posted [here](https://developer.xamarin.com/guides/xamarin-forms/user-interface/webview/#Local_HTML_Content) in my test project, but the iOS code does not seem to work. This is possibly why XLabs HybridWebView needed a workaround.

**Comment by SKLn-Rad** [comment]
Hey Alex, I will have a look into this a bit later if thats okay with you? I am still unsure on what would be the most optimal and simplest implementation for this feature as ideally I would love for people to have their local html in one place for example in the PCL and then be able to set the path to an assembly within their.
I probably also want to look into the possibility for Razor template support so I don't want to rush into a fix for this. 

In regards to the code not working in your example, are you testing on iOS 9.0 or above? There is another workaround needed for iOS 8 which could cause it to not work correctly as well.

**Comment by acicovic** [comment]
Hi Ryan,

By all means, think of it and take all the time you need. I'm all for well-thought features!

Regarding my tests, I am testing on iOS 10.2 in Visual Studio 2015 iPhone 6 Simulator. ASAP I will look a bit more into it, and upload the code to github.

**Comment by acicovic** [comment]
From my tests I conclude that you must add a "file://" prefix for it to work in iOS, (which is not mentioned in the aforementioned page). In case it is of any value to someone, this is the function I ended up with:

[assembly: Xamarin.Forms.Dependency(typeof(BaseUrl_iOS))]
namespace FormsWebViewTests.iOS
{
	public class BaseUrl_iOS : IBaseUrl
	{
		public string Get()
		{
			return "file://" + NSBundle.MainBundle.BundlePath + "/";
		}
	}
}

**Comment by acicovic** [comment]
In 1.3.1 I still need the file:// prefix in iOS. Android works without needing any special BaseUrl setting.

I am testing on iOS 10.2 in Visual Studio 2015 iPhone 6 Simulator.

**Comment by SKLn-Rad** [comment]
Thanks for all your testing! I will look more into it later but thats strange if its getting trimmed somewhere.
I presume its not a blocker for you anyway?

Aside from that, is the OnContentLoaded event doing as you expected?

**Comment by acicovic** [comment]
Hi,

It's not a blocker. The event does what I want in my preliminary testing. I will move it into my main app and let you know if I find any issues.
