### ISSUE TITLE
Cancelling Navigation

### ISSUE THREAD

**Issue by edmckee** [SKLn-Rad/Xam.Plugin.Webview#40]
I'm using your plugin specifically to disable navigation to specific urls.  I have the webview setup and I'm receiving the OnNavigationStarted events.  However when I cancel the navigation I still receive the message "ERR_UNKNOWN_URL_SCHEME.
My hope is that your plugin can support this and I've just implemented it wrong.
`internetContent.OnNavigationStarted += OnNavigationStarted;`

`        private NavigationRequestedDelegate OnNavigationStarted(NavigationRequestedDelegate eventObj)
        {
            Console.WriteLine(eventObj.Uri);
            if (eventObj.Uri.StartsWith("plaidlink://"))
                eventObj.Cancel = true;
            return eventObj;
        }`
![image](https://user-images.githubusercontent.com/349146/30163814-fed13376-939f-11e7-8ad6-be1bab24198c.png)

**Comment by SKLn-Rad** [comment]
Sorry I've only just seen this! Been manic at work recently.
What you are doing is completely correct, I am a tad confused as to why Android is handling it as such.

Would you be able to prepare me some sample code so I can get a better understanding as to the context of this bug? In the meantime I will have a look into the Android clients to see if I missed anything!

Regards,
Ryan

**Comment by SKLn-Rad** [comment]
Closing as no response. I did some work around this in 2.0.0 if you want to give that a try.
