### ISSUE TITLE
InputTransparent?

### ISSUE THREAD

**Issue by charlesroddie** [SKLn-Rad/Xam.Plugin.Webview#41]
Is it possible to get the InputTransparent property working on Xam.Plugin.Webview?
This would allow preventing users from interacting with static content (scroll, select) and allow adding TappedGestureRecognizers to the webview.

Currently it is not working on Windows 8.1, not tested on iOS and Anrdoid.

**Comment by charlesroddie** [comment]
Is this just a Windows issue? The fact that http://www.mrgestures.com/ doesn't work for Webviews on Windows suggests it may be. If so I will raise a bug on Xamarin bugzilla. Unfortunately they are 100x slower at fixing bugs than you are :).

**Comment by SKLn-Rad** [comment]
I'm fairly sure you're correct... Although it appears to be a problem with the webview "absorbing" manipulation events on the UWP platform.
For example: https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/15260955-enable-manipulation-events-for-webview

The work arounds I am currently using either involve Hammer.JS or involve binding the visibility property of a transparent boxview over the webview when the Input Transparency changes. Albeit this is REALLY ugly. What exactly are you trying to do with the webview if I can ask? I was tempted at one point to actually handle these in events using some fancy javascript so it might be an opportunity to do exactly that.

**Comment by charlesroddie** [comment]
Nice find.

We have webviews that are used to display formatted text (containing some LaTeX), and it would be nice to disable selection and scrolling (which cause minor glitches), and to select a corresponding object when you click on them, but it's also OK to have a button on the side for selection.

So it's not critical for us. We can try your boxview trick for now and wait for Windows to fix the issue.

Thanks!

**Comment by SKLn-Rad** [comment]
No problem, if you think Xamarin were slow at fixing issues however; you haven't seen Microsoft yet :(

Closing for now!

**Comment by charlesroddie** [comment]
BoxView trick works well!
