### ISSUE TITLE
Callback dictionaries

### ISSUE THREAD

**Issue by charlesroddie** [SKLn-Rad/Xam.Plugin.Webview#42]
Currently there is a static dictionary `RegisteredActions: Dictionary<object, Dictionary<string, Action<string>>>` for both global and local callbacks.

More natural would be:

- a static `Dictionary<string, Action<string>>` for the global callbacks
- instance `Dictionary<string, Action<string>>`s for local callbacks

Pros:

- Avoids memory management / memory leaks. Currently callbacks have to be deregistered manually when webviews are no longer needed. Without doing this, the static dictionary will grow, and if the dictionary references the unneeded webview, the webview will not be garbage collected. Having a local dictionary should allow garbage collection of a webview's dictionary.

Are there technical hurdles to this that led to the current approach?
Shall I try this change and send a PR?

**Comment by SKLn-Rad** [comment]
Honestly when I first put this in, it was a rushed feature for something I needed in an app! Any improvements I am more than welcome to and it certainly isn't optimal at the moment.
Feel free to submit a PR, and apologies for not getting back to you sooner.

- Ryan

**Comment by charlesroddie** [comment]
@SKLn-Rad I've done more work today on the events. Everything is now based on instance events.

Except for a static event RegisterGlobalActionsAddedDelegate in FormsWebView.

This event gets subscribed to in the renderers by all instances that get created.

Since the event stays alive, the instances stay alive, so there is a memory leak. (Even if there are no global callbacks as the subscription is still there.)

I think the right way to solve it is with a weak event. Microsoft has a WeakEventHandler but is strangely seems to be Windows only. I am looking at https://forums.xamarin.com/discussion/comment/19838#Comment_19838 now.
