### ISSUE TITLE
Callbacks in Android doesn't work

### ISSUE THREAD

**Issue by RayProfile** [SKLn-Rad/Xam.Plugin.Webview#44]
Hi,
First of all congratulations for this great plugin!
We've encountered a problem we can't seem to solve, maybe someone can help us!
We have a TabbedPage App  with NavigationPage. In every tab a ListView calls the same page model with different data. In this page we dynamically create some HTML code which goes to the 'abstractions:FormsWebView' through 'xamlWebView.Source = HTML_CODE'.
On the 'OnContentLoaded' event we register all the callbacks with 'xamlWebView.RegisterLocalCallback' in order to call C# from the WebView.
In iOS everything works flawlessly, in Android the callback doesn't respond, as if the javascript bridge is completely missing in the webview...

The only error we get is:
`[chromium] [INFO:CONSOLE(1)] "Uncaught ReferenceError: bridge is not defined", source:  (1)`

Everything else works fine, the App doesn't crash and all the natives functions works but the callback just won't respond..
Thanks!

**Comment by SKLn-Rad** [comment]
Hey man, thats very odd! I know a ton of people using them with no problem. Would you be able to shoot me some code to see how you managed to get this bug?

Note: One of my contributors did some work on callbacks recently for 1.8.0, it might be worth giving that release a go first to see if that fixes anything.

~ Ryan

**Comment by RayProfile** [comment]
Hi Ryan,
Thanks for the quick response, we've just tried on 1.8.0 and the error persists..
Here's some code, it's shared between iOS and Android and on iOS it works just fine.

```
<abstractions:FormsWebView x:Name="xamlWebView" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" ContentType="StringData" BackgroundColor="#FFF"  />


// C# CODE

//set my dynamic HTML Source
xamlWebView.Source = HTML_CODE;
xamlWebView.OnContentLoaded += OnContentLoaded;


private void OnContentLoaded(ContentLoadedDelegate eventObj)
{
	eventObj.Sender.RegisterLocalCallback("open_new_native", (string str) => my_callBack(str));
}
		
private void my_callBack(string s)
{
	System.Diagnostics.Debug.WriteLine("my_callBack"+s);
	//...
}


// JAVASCRIPT CODE
$(document).ready(function(){
	
	//...
	//
	$('body').on('click touchend', '.link-extra' , function(e) {
		e.preventDefault();
		var id_link = $(this).attr('id');
		open_sk('ExtraList_'+id_link);
		
	});
	//
	//...

});
//...
function open_sk(link_sk){
	
	console.log("########### --- "+ link_sk +" ----- #######");
	
	// ERROR HERE
	open_new_native(link_sk); 	// [chromium] [INFO:CONSOLE(1)] "Uncaught ReferenceError: bridge is not defined", source: (1)
	// ERROR HERE
	
}
//...
```
Thanks a lot!
Ray

**Comment by SKLn-Rad** [comment]
Ah StringData! I think I might know whats going on here. I have a feeling the Android Chrome Client isn't treating it as a normal HTTP request and might be ignoring the Navigation event as a result. Will get back to you, when did you need this done by? Is tomorrow okay?

**Comment by RayProfile** [comment]
Yeah, tomorrow is absolutely fine!
Thanks a lot!

**Comment by RayProfile** [comment]
So, we've tried with a static HTML "ContentType: localfile" and it works as it should in iOS and Android...however we really need to use HTML code generated in C# and StringData looks like the way to go. Any workaround would be greatly appreciate as well 😃 
Thanks,
Ray

**Comment by SKLn-Rad** [comment]
I did some refactoring. And by some, I mean ALOT.
Give 2.0.0 a go, but make sure to read the migration guide on here before doing so.

I worked callbacks from the ground up, but if these still don't work give InjectJavascriptAsync a go. I added a sample in the Sample Application which does what you want it to do!

Let me know if you have any issues. 👍

**Comment by RayProfile** [comment]
Hey Ryan, great work!
We're still testing it but it looks like is now working perfectly on Android.
However it seems like we've lost the BaseUrl references in iOS.
Css and Js files are located in the Resources folder as a bundle resource.
Works fine in Android (where of course files are located in the Assets folder as Android assets).
Any idea?

**Comment by RayProfile** [comment]
My bad, we've fixed the BaseUrl and it's now working perfectly!
Thank you very much for your help!!

**Comment by SKLn-Rad** [comment]
No problem! I was worried then as I couldn't actually find the issue haha. closing.
