### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by StanleyBroo** [SKLn-Rad/Xam.Plugin.Webview#47]
Love the plugin ;-)  

App crashed when navigating away from the page while webview content hadn't finished loading ..but
I was using 1.7.0 and have now updated to 2.0.5. Get back if the issue comes back.

**Comment by SKLn-Rad** [comment]
I noticed this pretty much straight away!
Can you give 2.0.5 a go? Been pumping out tons of minor fixes in the last few hours.

**Comment by StanleyBroo** [comment]
Thanks!

**Comment by StanleyBroo** [comment]
FormsWebView work great in Xamarin Shared. Have a local.AndroidResource html file which we load the new BingMap V8 Map into..works great with InjectJavascriptAsync for adding pushpins etc.

Question how can we use the same approach for viewing a .pdf ? ..without adding a html + js libs on a actual server. Is this possible with FormsWebView.


Best rgds, stanley broo
