### ISSUE TITLE
How to call C# from Javascript

### ISSUE THREAD

**Issue by atultiwari** [SKLn-Rad/Xam.Plugin.Webview#48]
Hi,

First of all congratulations and thank you for this wonderful plugin. I want to use this plugin to show a multiple choice question (as labels can't show HTML content), but I am having difficulty on how to get value in C# from Javascript.
My sample HTML code with Javascript is -
```

<html>
<body>

<div id="question">What is your age?</div>
<div id="options">
<label><input type="radio" name="option" value="1" onclick="CallCSharpFunction()"> 10 years</label>
<label><input type="radio" name="option" value="2" onclick="CallCSharpFunction()"> 20 years</label>
<label><input type="radio" name="option" value="3" onclick="CallCSharpFunction()"> 30 years</label>
<label><input type="radio" name="option" value="4" onclick="CallCSharpFunction()"> 40 years</label>
</div>

<p id="selectedOption"></p>

<script>
function CallCSharpFunction() {
	var options = document.getElementsByName('option');
	var option_value;
	for(var i = 0; i < options.length; i++){
		if(options[i].checked){
			option_value = options[i].value;
		}
	}
	document.getElementById("selectedOption").innerHTML = option_value;
	//What should I do to inform C# the selected option's value?
}
</script>

</body>
</html>
```

I am sorry to ask this lame question, but I am quite new in programming. **From the above HTML sample code, how to should should I receive the selected option's value in C# for further use?**

Thanks

Atul

**Comment by SKLn-Rad** [comment]
Hey man, sorry for the massive delay! I have been on holiday over the weekend and have been catching up all today.

Simple answer, add a callback.
Here is an example: https://pastebin.com/1HNyVNCL

Note, I used your code, so it will return the value assigned with the radio, and not the text in the label. But it works none the less.

Let me know if this is what you meant, so I can close this 👍

**Comment by atultiwari** [comment]
@SKLn-Rad Thank you very much. I was looking for the same.
