### ISSUE TITLE
401 on Android Device, but iOS is working fine

### ISSUE THREAD

**Issue by PSyron** [SKLn-Rad/Xam.Plugin.Webview#51]
Hi, 
I'm trying to add header token to request.
iOS is working fine.

I have Internet permission on my my droid project and did initialise on beginning.

MainActivity
`
  protected override void OnCreate(Bundle bundle)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(bundle);

            FormsWebViewRenderer.Initialize();
            global::Xamarin.Forms.Forms.Init(this, bundle);
            LoadApplication(new App());
        }
`

Still I'm getting 401 on emulator and device. 

Any clue what I've missed? Thanks

**Comment by PSyron** [comment]
I've logged problem with charles. 

`if (!browser.LocalRegisteredHeaders.ContainsKey("Authorization"))
            {
                browser.LocalRegisteredHeaders.Add("Authorization", Helpers.ApiHelper.AUTHORIZATION_SCHEMA + " " + Settings.UserToken);
            }`

Im setting bearer token. It's case sensitive but somehow library is making all lowercase in header :O

**Comment by PSyron** [comment]
foreach (var header in Element.LocalRegisteredHeaders)
            {
                if (!headers.ContainsKey(header.Key.ToLower()))
                    headers.Add(header.Key.ToLower(), header.Value.ToLower());
            }

this is problem in library Xam.Plugin.Webview/Xam.Plugin.WebView.Droid/FormsWebViewRenderer.cs

**Comment by SKLn-Rad** [comment]
Yes, only the name should be case-insensitive! Fixing it now; give me 20 minutes as I need to build for MacOS and that involves me running to the other side of the office for an iMac 👍 Thanks for the find.

**Comment by PSyron** [comment]
No problem but are You sure u want lowercase key as that is not changing anything, just another operation. Isn't it better to leave it as user specify it? Less operation and more flexibility. Event if that changes nothing. Its consistent with GlobalHeader then. Thanks for fix!

**Comment by SKLn-Rad** [comment]
Yeah I am completely removing that. The idea I think drunken me had originally was that the Android webview would crash if you had two header keys with the same name but different cases. I am just going to let that fail as that would be user error anyway.

Checking in this:

// Add Local Headers
            foreach (var header in Element.LocalRegisteredHeaders)
            {
                if (!headers.ContainsKey(header.Key))
                    headers.Add(header.Key, header.Value);
            }

            // Add Global Headers
            if (Element.EnableGlobalHeaders)
            {
                foreach (var header in FormsWebView.GlobalRegisteredHeaders)
                {
                    if (!headers.ContainsKey(header.Key))
                        headers.Add(header.Key, header.Value);
                }
            }

**Comment by SKLn-Rad** [comment]
https://www.nuget.org/packages/Xam.Plugin.WebView/2.0.8
Give it some time to index, and get back to me just to let me know that I haven't done anything dumb and forgotten anything. :)

**Comment by PSyron** [comment]
Thanks! Looking forward to see it. 
FYI. Your library will be used in project for one of the biggest company in Europe ;) 
Have a great day Ryan

**Comment by SKLn-Rad** [comment]
Haha, I've heard that a lot. Weird how a lot of big companies are still using Hybrid apps :)
You to, I will leave this ticket open and presume if I havent heard back; then I will close it

**Comment by PSyron** [comment]
Simple app from a big food company to show online docs. Need credentials to use it in header.

We have native apps for them but they are going into hybrids now. Strange how many people are trusting React Native just because Facebook using it for Messenger and instagram, but it is still below version 1

**Comment by PSyron** [comment]
iOS have problem after going to 2.0.8

In appDelegate app cannot find   FormsWebViewRenderer for 
`  FormsWebViewRenderer.Initialize();`

**Comment by SKLn-Rad** [comment]
Okay, somehow Nuget "pack" missed the missing files in the files tag.
Apologies, normally it would complain if this were the case.

https://www.nuget.org/packages/Xam.Plugin.WebView/2.0.9
I manually verified all the .dll's are in the package this time... :(

**Comment by PSyron** [comment]
I have problem today.
 Failed to read 'xxx/Droid/obj/Debug/android/assets/Xam.Plugin.WebView.Droid.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.

Cannot deploy droid with library. Nothing change related to this library or project configuration
