### ISSUE TITLE
Compilation error: Xam.Plugin.WebView.Droid.dll.mdb does not match assembly

### ISSUE THREAD

**Issue by rc183** [SKLn-Rad/Xam.Plugin.Webview#53]
Hi,

I have an error when I try to compile for Android : 

Mono.CompilerServices.SymbolWriter.MonoSymbolFileException: Symbol file `D:\...\Xam.Plugin.WebView.Droid.dll.mdb' does not match assembly
   à Mono.CompilerServices.SymbolWriter.MonoSymbolFile.ReadSymbolFile(String mdbFilename, Guid assemblyGuid)
   à Mono.Cecil.Mdb.MdbReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName)
   à Mono.Cecil.Cil.DefaultSymbolReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName)
   à Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   à Mono.Cecil.ModuleReader.CreateModule(Image image, ReaderParameters parameters)
   à Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   à Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)		

I don't understand why ? My minSdkVersion in the manifest is 21.

Any ideas ?

Thank you !
 Régis

**Comment by SKLn-Rad** [comment]
I'm fairly sure its just my build process leaving artefacts! clean doesn't remove the bin/obj directories so I just did a fresh build to include some other bug fixes. Give 2.0.10 a go.
https://www.nuget.org/packages/Xam.Plugin.WebView/2.0.10

Also, apologies for the huge delay.

**Comment by SKLn-Rad** [comment]
Closing as no response and no further complaints
