### ISSUE TITLE
DecisionHandlerDelegate does not provide full URL on iOS

### ISSUE THREAD

**Issue by FlammableFork** [SKLn-Rad/Xam.Plugin.Webview#54]
Suppose in my WebView, I am working with https://example.com, and I have the following event handler for the OnNavigationStarted event:

```csharp
private void OnNavigationStarted(object sender, DecisionHandlerDelegate e) { }
```

When this handler is triggered, the Uri provided inside the DecisionHandlerDelegate is always just the base domain URL.  As an example, if I am trying to navigate to https://example.com/settings, e.Uri only ever equals https://example.com, and loses the remainder of the URL.

Android and UWP work perfectly, providing the entire URL being navigated to.  Also, this issue appeared only after upgrading to 2.0+.  Versions before 2.0 worked properly, but they were using a different delegate.

**Comment by SKLn-Rad** [comment]
Found it! Yes that was my fault, during the swap other to netstandard I rewrote a few of these delegate. Turns out in the iOS one I am calling renderer.Element.Source instead of renderer.Control.Uri.

I can get a fix out, but it would have to be when a Mac is free in the office, is later today too late for you?

**Comment by SKLn-Rad** [comment]
Give this release and go and let me know if it sorts it for you, I tested with the sample code I added and it appears to work fine.
https://www.nuget.org/packages/Xam.Plugin.WebView/2.0.10

**Comment by FlammableFork** [comment]
Thank you for fixing this.  I can see the full URL coming through, which is awesome.  There does seem to be another odd issue, however.  It seems that my OnNavigationStarted event handler is being invoked twice.  The first time, the delegate contains the current Uri, and then the second time it contains the Uri I wish to navigate to.  Is there something that would be firing the OnNavigationStarted event twice?  As before, this is only affecting iOS.  I checked Android and UWP, and the event handler is only being invoked once, as expected.  Thanks.

**Comment by SKLn-Rad** [comment]
Can't see any immediate cause from looking at the handler @line 24 here: https://github.com/SKLn-Rad/Xam.Plugin.Webview/blob/ebd3d5fb2ad5875fca52a80ccb5a78a10a730a6f/Xam.Plugin.WebView.iOS/FormsNavigationDelegate.cs

Do you have more than one webview present (i.e not disposed off).
When I get time I will have a look into this, but I presume its not blocking you currently?

**Comment by FlammableFork** [comment]
No, I only have a single WebView in use.  It is slightly interfering with my Uri checks, but it is not blocking me from continuing.  For the time being, I will simply make an additional check to see if the Uri being passed in the delegate is the same as the currently loaded Uri.  Thanks.

**Comment by FlammableFork** [comment]
After some more debugging, it does sort of seem like there are two copies of the WebView, at least just for iOS.  When the OnNavigationStarted event fires, the first time the event handler is invoked, the entire object is an old version.  The delegate contains the current Uri, but the WebView itself contains all of the previous navigation's information.

For example, if I first navigated to https://example.com then to https://example.com/item1, ignoring the event, but then I try to navigate to https://example.com/item2, breaking in the handler, the first time the handler is invoked, the delegate Uri is https://example.com/item1 and the WebView's Source is set to https://example.com.  The second time the handler is invoked, the delegate Uri is http://example.com/item2 and the WebView's Source is set to http://example.com/item1, which is what I would expect.  It is as if I have an old version of the WebView and a new version of the WebView, and both versions' handlers are being invoked, despite supposedly being the same object.  Very weird.

I did attempt to do a reference equality check between the senders of the two invocations of the handler, but that passed, claiming that the sender in both invocations was the same.  I am at a loss.  Thanks.

**Comment by SirLanceLang** [comment]
I dont know if it is the same problem, but it seems like that the DecisionHandlerDelegate in OnNavigationStarted is sending the current URL and not the URL whereto I am navigating. So If i have loaded "www.google.com" and I navigating to a llink on googles page "www.google.com" will be sent in the DecisionHandlerDelegate  as Uri.

**Comment by SirLanceLang** [comment]
Hi Ryan,
I have just tested it in 2.11, 2.06, 1.8 and1.7.
In 1.8 and 1.7 it is working as expected. After 1.8, not working anymore. :(

**Comment by FlammableFork** [comment]
Things appear to be working the way I expect them to in (at least) version 2.1.2.  Thank you.

**Comment by SirLanceLang** [comment]
Here as well.
