### ISSUE TITLE
Changing source doesn't trigger navigation on iOS

### ISSUE THREAD

**Issue by FlammableFork** [SKLn-Rad/Xam.Plugin.Webview#55]
I haven't been able to determine if this is a problem all the time, or only in the instance I am doing this.  I have the following event handler for the OnNavigationStarted event:

```csharp
private void OnNavigationStarted(object sender, DecisionHandlerDelegate e)
```

During the course of this handler, if certain conditions exist, I cancel the current navigation and attempt to start navigation to another URL.  As an example (condensed), I have the following code when the conditions are met:

```csharp
e.Cancel = true;
(BindingContext as ViewModel).Url = e.Uri;
```

Setting the bound property in my view model fires the PropertyChanged event.  Android and UWP both intercept this property change and redirect the WebView to the URL desired.  iOS does nothing.  I have also tried the following:

```csharp
e.Cancel = true;
(sender as FormsWebView).Source = e.Uri
```

This also yields the same results.  iOS simply does nothing.  Thoughts?  Thanks.

**Comment by SKLn-Rad** [comment]
To be honest I haven't noticed any issues in my usage of this, although I don't cancel the navigation and reset the uri in the OnNavigationStarted event; so I presume its down to this scenario.
I will try and get around to having a look at this today, hopefully for the same build as the other fix you requested as I doubt its much work.

Ry

**Comment by SKLn-Rad** [comment]
This is due to the webview still being in a "Navigating State", both iOS and newer versions of Android do it.
You should instead only cancel navigation in OnNavigationStarted and change your source after OnNavigationCompleted is fired.

Closing due to not supported

**Comment by FlammableFork** [comment]
Thanks for looking into this though.  To be honest, I hadn't noticed that you could change the Uri in the delegate during the event handler.  In my app, I actually have user interaction at this time (when the criteria is met), so I still wanted to cancel the current navigation while I waited for the input.  I got around this issue by awaiting a new Task which contained my user interaction logic and set the Uri after user input was received.  Awaiting the Task allowed the event handler to exit properly and immediately.
