### ISSUE TITLE
OnContentLoaded & OnNavigationCompleted are not fired on version 2.0.11 and IOS 11

### ISSUE THREAD

**Issue by engramyosama6** [SKLn-Rad/Xam.Plugin.Webview#58]
I am trying to do some actions after the content is loaded but the events are not being fired at all

**Comment by SirLanceLang** [comment]
I have upgraded to the latest version and both events are being fired. Have you cleaned the solution?

**Comment by SKLn-Rad** [comment]
Thats odd, I have tested this a lot before I deployed the build.
did it work previously? and if so what has changed? Different versions? Different iOS version? Different device?

**Comment by SirLanceLang** [comment]
Hi Ryan,
I have just tested it in 2.11, 2.06, 1.8 and1.7.

In 1.8 and 1.7 it is working as expected. After 1.8, not working anymore. :(

**Comment by SKLn-Rad** [comment]
Strange, its working for myself! Can you give me some sample code if its not too much of a problem for you? I will have a look at the change logs to see if I can figure out whats going on

**Comment by SirLanceLang** [comment]
Ryan, I am sorry. What I was answering to in this thread was actually regarding a question I made in another thread. I can see now that you were asking @engramyosama6 .
As I stated before the two events are working for me.
Sorry about the confusion.

**Comment by engramyosama6** [comment]
Yes for me it was working on 1.6 after that it didn't work, right now when i downgrade it fires but i get NSError exception and the app crash.

**Comment by engramyosama6** [comment]
I have this in the xaml

<fwv:FormsWebView x:Name="webview"  ContentType="Internet" HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" RelativeLayout.WidthConstraint="{ConstraintExpression Type=RelativeToParent, Property=Width}" RelativeLayout.HeightConstraint="{ConstraintExpression Type=RelativeToParent, Property=Height}" OnNavigationCompleted="Handle_OnNavigationCompleted" OnContentLoaded="Handle_OnContentLoaded"/>

**Comment by engramyosama6** [comment]
Also I have the latest Xamarin Mono framework and IOS 11 if this can help you

**Comment by engramyosama6** [comment]
My bad after I updated I didnt change the xaml header for the new version
