### ISSUE TITLE
[Android] Initial navigation doesn't invoke OnNavigationStarted when network is down

### ISSUE THREAD

**Issue by FlammableFork** [SKLn-Rad/Xam.Plugin.Webview#65]
I have code that handles network availability errors inside my OnNavigationStarted handler.  This has been working very well.  However, I just noticed that if the network is already down when the FormsWebView is initialized, the event OnNavigationStarted is never fired.

When I initialize the FormsWebView with the network up and operating the event fires properly when initializing, and then if I  disable the network, the event continues to fire properly on subsequent navigations.

The problem seems to only surface while initializing while the network is already down.  If I initialize with the network down, then the OnContentLoaded event is firing for a page that isn't really loaded (perhaps a different issue?) and breaks the initial navigation without having been able to catch the issue in the un-triggered OnNavigationStarted handler.

**Comment by SKLn-Rad** [comment]
I'm starting to think this is a native issue in the underlying webview.
Can I ask if you can reproduce this in a simulator? If so, what image are you using and Android version. I will try and hunt this down if I can later this week!

**Comment by FlammableFork** [comment]
Well, I just tested in the emulators, and everything appeared to be working properly.  I then went back to the physical device, and the issue is suddenly gone.  I went through many tests earlier while trying to figure out the issue, so I'm not sure what happened to make it work (although I am pleased it is working).  Sorry to waste your time.  Thanks though!
