### ISSUE TITLE
Is it possible providing a method to return the rendered html code?

### ISSUE THREAD

**Issue by oienwav** [SKLn-Rad/Xam.Plugin.Webview#67]
for some reasons I need to get the html source code.

**Comment by SKLn-Rad** [comment]
You mean like this helper method?

public static Task<string> GetCurrentHtmlAsync(this FormsWebView webView) {
    return await webView?.InjectJavascriptAsync("document.getElementsByTagName('html'[0].innerHTML")) ?? string.Empty;
}

I could potentially add it potentially in the form of a utility/helper class, I use it myself anyway!
What do you think?

**Comment by oienwav** [comment]
that's greate,thank you for your help.
by the way,do you know how to disable web security for the crossdomain issue.
