### ISSUE TITLE
JavaScript debugging

### ISSUE THREAD

**Issue by abrasat** [SKLn-Rad/Xam.Plugin.Webview#70]
Is it possible to debug the JavaScript code loaded through a page in Webview in VisualStudio, for Xamarin.Forms projects targetting iOS and Android?
For UWP I am changing the DebuggerType of the Application Process in the project debug options to "Script". Could not find a way how to debug scripts on iOS and Android.

**Comment by SKLn-Rad** [comment]
I believe chrome and safari have remote debuggers built in to do this!

I can't remember exactly how on iOS, but on Android you do the following:
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/
