### ISSUE TITLE
How to change BaseUrl

### ISSUE THREAD

**Issue by acicovic** [SKLn-Rad/Xam.Plugin.Webview#9]
Hi Ryan,

I am running 1.3.0.

In one of my tests iOS crashes, and I suspect that changing the BaseUrl will fix the issue. However, I am unable to understand how to change the BaseUrl. I went into AppDelegate.cs and attempt to change BaseUrl after the FormsWebViewRenderer.Init() call (I figured there would be some FormsWebViewRenderer.BaseUrl property), but the property does not show up.

I am obviously doing something wrong. Can you provide me an example or tell me where to look at?

Thanks!

**Comment by SKLn-Rad** [comment]
Rookie mistake on my half! I didn't make those fields public for you.
Update to 1.3.1 and then it should be done exactly as you said.

Also worth noting, in iOS is will automatically not put the prefixing file:// so you no longer need that, just supply the base path. By default it is NSBundle.MainBundle.BundlePath
